apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  tags:
    - python
    - flask
spec:
  type: service
  owner: ${{ values.owner }}
  lifecycle: experimental