apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ parameters.name }}
  description: ${{ parameters.description }}
  annotations:
    github.com/project-slug: ${{ parameters.owner }}/${{ parameters.name }}
spec:
  type: service
  owner: ${{ parameters.owner }}
  lifecycle: experimental